language: node_js
node_js:
  - 14

branches:
  only:
  - main

notifications:
  email: false

install:
  - npm install

script:
  - npm run build
  - git checkout --orphan gh-pages
  # - git rm --cached -r . &> /dev/null
  - git rm --cached -r .
  - mv public/* .
  - rm -rf package* rollup* tsconfig* src/ .travis* public/
  - echo "cordiais.marinagem.com" > CNAME
  - git add .
  - git commit -m "updates site" &> /dev/null
  - git remote add gh https://thiagohersan:$GHTOKEN@github.com/the-happy-team/cordiais-web.git
  - git push gh :gh-pages
  - git push gh gh-pages
