export const emotions = {
  en: {
    happiness: "happiness",
    surprise: "surprise",
    sadness: "sadness",
    disgust: "disgust",
    anger: "anger",
    fear: "fear",
    neutral: "neutral",
  },
  pt: {
    happiness: "felicidade",
    surprise: "surpresa",
    sadness: "tristeza",
    disgust: "nojo",
    anger: "raiva",
    fear: "medo",
    neutral: "neutro",
  },
};

export const menu = {
  en: {
    about: "about",
    sort: "arrange by emotion",
    highlight: "highlight",
    texts: "texts",
    contact: "contact",
    happiness: "happiness",
    surprise: "surprise",
    sadness: "sadness",
    disgust: "disgust",
    anger: "anger",
    fear: "fear",
    neutral: "neutral",
    FemaleArtist: "by female artist",
    MaleArtist: "by male artist",
    Nudes: "by nudes",
  },
  pt: {
    about: "sobre",
    sort: "organizar por",
    highlight: "destaques",
    texts: "textos",
    contact: "contato",
    happiness: "felicidade",
    surprise: "surpresa",
    sadness: "tristeza",
    disgust: "nojo",
    anger: "raiva",
    fear: "medo",
    neutral: "neutro",
    FemaleArtist: "por artistas mulheres",
    MaleArtist: "por artistas homens",
    Nudes: "por nudes",
  },
};
